### ISSUE TITLE
Error with CCMgen --tree-newick 

### ISSUE THREAD

**Issue by odannis** [soedinglab/CCMgen#6]
Hi,

I am trying to use CCMgen with a tree inferred by [fasttree2](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0009490). 

Two problems :

1)
     The "intermediate" clades (not the leaf) of the tree inferred have no names (None). That creates an error in the generation of sequence : 
      `  File "/home/andonis/anaconda3/lib/python3.8/site-packages/ccmpred/sampling/__init__.py", line 169, in sample_to_neff_increasingly
          msa_sampled = np.empty((nseq, ncol), dtype="uint8")
      TypeError: 'NoneType' object cannot be interpreted as an integer
      `

      To avoid this error, I changed the function `def split_tree(tree, id0):` in the file trees.py. I replaced : 
      `id_to_node = dict((cl.name, cl) for cl in bfs_iterator(tree.clade))`
      by
      `id_to_node = dict((cl.name,cl) for cl in bfs_iterator(tree.clade) if not cl.name is None )`
      
2)
      The tree inferred by fasttree has no clade with the name "root". So, I added the name "root" to the first clade : 
      ```from Bio import Phylo
      tree = Phylo.read("file.fasta.tree","newick")
      tree.clade.name = "root"
      tree.clade.branch_length = 0
      Phylo.write(tree,"file_root.fasta.tree","newick")
      ```

Now, if I do
`ccmgen 1atzA.braw.gz  new_msa.fas    --tree-newick file_root.fasta.tree     --alnfile file.fasta     --mcmc-sample-random-gapped --mcmc-burn-in 0  --mutation-rate-nef` 
the program properly finished. But, I am scared that I over simplified my tree with my solution 1) 

Thank you for your help!

**Comment by odannis** [comment]
**[Link](https://upload.disroot.org/r/nt3LMMJ1#SzjyEQluY5Ur4XVWVKPo/T4HhP25B6boyUPTVhMO4RA=)** for the file if you want to reproduce the error

**Comment by croth1** [comment]
Hi @odannis,

CCMgen is a bit restrictive when it comes to the newick format. As you already realised, the root node's label is `root`, the leaf nodes need to be integers that represent the position in the MSA and the internal nodes have to be named, but the name itself is not of importance. The following would be a valid input to CCMgen. Here the internal nodes were assigned random uuids.

>(((0:0.39069,1:0.31737)dbf15fd9-b633-4ef2-ba1b-7a53968eb62d:0.27912,(2:0.40812,3:0.50920)fb32eeb4-513a-4063-ab10-ddbad71e5d78:0.39598)c193ccc3-e1a6-431a-acce-068fa70738a2:0.36127,((4:0.30630,5:0.30630)b9c4a9dd-57e1-4e84-b134-e748b5be9b3a:0.27982,(6:0.51569,7:0.42195)9f60b3ad-ac66-420d-bfe8-394bd2f446ed:0.27956)7c63c71a-cb6c-4c37-869a-326162c9282c:0.11241)root:0.00000;

I feel like the easiest solution is to write a short script that reads in the newick file from fasttree2, reformats it according to these constraints and writes it out again. This should not take more than 10-20 lines of code, I feel.

**Comment by odannis** [comment]
Thank you for your answer! 

I wrote this little code : 

```
import uuid
from Bio import Phylo
import sys

def modify_clades(clade_root,pos_msa):
    b = clade_root.clades
    if len(b)>0:
        for clade in b:
            clade.name = str(uuid.uuid1())
            modify_clades(clade,pos_msa)
    else:
        clade_root.name = str(pos_msa[0])
        pos_msa[0] += 1

def write_new_tree_for_ccmgen(file_tree, file_new_tree):
    print("Tree used : ", file_tree)
    tree = Phylo.read(file_tree,"newick")
    pos_msa = [0]
    modify_clades(tree.clade, pos_msa)
    tree.clade.name = "root"
    tree.clade.branch_length = 0
    print("New Tree to use : ", file_new_tree)
    tree = Phylo.write(tree,file_new_tree,"newick")
```

You just have to do : ` write_new_tree_for_ccmgen(file_tree,file_new_tree)`
If anyone want to use it, feel free to do it !
