### ISSUE TITLE
How to use --seq0-file option ? 

### ISSUE THREAD

**Issue by odannis** [soedinglab/CCMgen#8]
Hi,

I would like to sample sequence on a tree by starting from a random sequence (instead of polyA sequence). For doing that, I am creating a fasta file with one random sequence that I use with --seq0-file option.

```
ccmgen --tree-newick my.tree  --seq0-file  seq0_file.fasta --mutation-rate 1 1atzA.braw.gz msa.fas
 ```

In the output, I see : 
`Ancestor sequence (polyA --> 10 gibbs steps --> seq0) :`
which means that the option `--seq0-file` is not considered. 

Have you any idea why? I am adding the file to reproduce this issue [url file](https://upload.disroot.org/r/BA8q8XJV#bm8h7o34Sqr0gNYGSeroLIjaFSQMPvNlsJ0CfillvUI=)

Thank you for your help ! 

The total output of this command is :
```
  ┏━╸┏━╸┏┳┓┏━╸┏━╸┏┓╻  version 1.0.0
  ┃  ┃  ┃┃┃┃╺┓┣╸ ┃┗┫  Vorberg, Seemayer and Soeding (2018)
  ┗━╸┗━╸╹ ╹┗━┛┗━╸╹ ╹  https://github.com/soedinglab/ccmgen

Using 36 threads for OMP parallelization.

Successfully loaded model parameters from /home/gerardos/analyse_sequence/Code_for_cluster/field_ccmpred/1atzA.braw.gz.
Created newick tree with 23633 leaves, 41705 nodes, avg branch length=0.091, depth_min=7.4035e-01, depth_max=4.2180e+00

Ancestor sequence (polyA --> 10 gibbs steps --> seq0) :
AKSQFVAAISHELQSPLNAILMFSRILSRLTEHGREAFGDIRRSGMHALELIDGLLRFSRIEAGVLIIEDNGADRHGMSLLLESTGAQRVADAATGERGLQAFRAGGLGCVLVDLSLPGRSGQAMIGAIQEADRRIPAIVISGHVDAQAVRRCMRFGAEAFLTKPFEPSVLAEAVN
avg number of amino acid substitutions (parent -> child): 16.0

Alignment with 23633 sequences was sampled with mutation rate 1.0 and has Neff 4.08072
```

**Comment by croth1** [comment]
Hi @odannis,

I think there's currently a quirk in the logic how the `--seq0-file` option is parsed. I have a hunch that if you change:

`if opt.seq0_mrf:` -> `if opt.seq0_mrf and not opt.seq0_file:`

here: https://github.com/soedinglab/CCMgen/blob/master/ccmpred/scripts/run_ccmgen.py#L191

it might work - I cannot promise that I can test and fix this in the near future though.
